import React from 'react';
import {appearanceDefaults,appearanceStyle,colorPresets,skins} from './ui/skins.mjs';
import FeedbackSettings from './feedback_settings.jsx';

export default function AppearancePage({preferences,updatePreferences}) {
  const appearance={...appearanceDefaults,...preferences};
  const slider=(key,label,min,max,step=1,percent=false)=><label className="setting-field" key={key}><span>{label} · {percent?Math.round(appearance[key]*100)+'%':appearance[key]}</span><input aria-label={label} type="range" min={min} max={max} step={step} value={appearance[key]} onChange={e=>updatePreferences({[key]:Number(e.target.value)})}/></label>;
  return <main className="settings-page appearance-page"><header className="page-heading"><h1>Appearance</h1><button onClick={()=>updatePreferences(appearanceDefaults)}>Reset appearance</button></header>
     <nav className="appearance-links" aria-label="Appearance sections">{[['look','Style'],['windows','Windows'],['colors','Colors'],['feedback','Speech & listening']].map(([id,label])=><a key={id} href={'#appearance-'+id} onClick={event=>{event.preventDefault();document.getElementById('appearance-'+id)?.scrollIntoView({block:'start'});}}>{label}</a>)}</nav>
     <section className="settings-content"><h2 id="appearance-look">Style</h2><p className="caption">Changes apply to all windows as you make them.</p><div className="skin-options">{skins.map(skin=><button key={skin} className={'skin-preview skin-'+skin+(appearance.skin===skin?' selected':'')} aria-pressed={appearance.skin===skin} style={appearanceStyle(appearance)} onClick={()=>updatePreferences({skin})}><span className="skin-mini"><i/><i/><i/></span><strong>{skin==='glass'?'Liquid glass':skin[0].toUpperCase()+skin.slice(1)}</strong></button>)}</div>
     <h2 id="appearance-windows">Windows</h2><p className="caption">Mini and collapsed backgrounds stay transparent. Full view also blurs the desktop on supported Windows versions. Glass blur controls panel blur; set it to zero to disable full-view background blur too.</p>
     <div className="settings-grid">{slider('glassOpacity','Glass panel opacity',.35,1,.01,true)}{slider('glassBlur','Glass blur',0,48)}{slider('cornerRadius','Corner roundness',0,28)}
     <label className="setting-field toggle-field"><span>Reduce motion<small>Use fewer visual transitions.</small></span><input type="checkbox" role="switch" checked={appearance.reduceMotion} onChange={e=>updatePreferences({reduceMotion:e.target.checked})}/></label>
     <label className="setting-field toggle-field"><span>Advanced explanations<small>Show technical notes and setting names.</small></span><input type="checkbox" role="switch" checked={appearance.advancedExplanations} onChange={e=>updatePreferences({advancedExplanations:e.target.checked})}/></label></div>
    <h2>Color presets</h2><div className="color-presets">{Object.entries(colorPresets).map(([name,colors])=><button key={name} onClick={()=>updatePreferences(colors)}><i style={{background:colors.background}}/><i style={{background:colors.accent}}/>{name[0].toUpperCase()+name.slice(1)}</button>)}</div>
     <h2 id="appearance-colors">Colors</h2><div className="settings-grid">{[['background','Background'],['surface','Surfaces'],['accent','Accent'],['text','Text'],['muted','Secondary text'],['gradientStart','Gradient start'],['gradientEnd','Gradient end']].map(([key,label])=><label className="setting-field color-field" key={key}><span>{label}</span><div><input type="color" aria-label={label+' color'} value={appearance[key]} onChange={e=>updatePreferences({[key]:e.target.value})}/><code>{appearance[key]}</code></div></label>)}</div>
    <div className="settings-grid appearance-sliders"><label className="setting-field"><span>Gradient direction · {appearance.gradientAngle}°</span><input aria-label="Gradient direction" type="range" min="0" max="360" value={appearance.gradientAngle} onChange={e=>updatePreferences({gradientAngle:Number(e.target.value)})}/></label><label className="setting-field"><span>Glass opacity · {Math.round(appearance.glassOpacity*100)}%</span><input aria-label="Glass opacity" type="range" min="0.35" max="1" step="0.05" value={appearance.glassOpacity} onChange={e=>updatePreferences({glassOpacity:Number(e.target.value)})}/></label></div>
     <p className="caption">Your choices are saved on this computer. The avatar and video stay transparent; their colors are not changed.</p>
      <div id="appearance-feedback"><FeedbackSettings preferences={preferences} update={updatePreferences}/></div>
    </section></main>;
}
