import test from 'node:test';
import assert from 'node:assert/strict';
import {Bone,Group,Vector3,Quaternion,Texture,Mesh,MeshBasicMaterial,BoxGeometry} from 'three';
import {AvatarGesture,AvatarHover} from './avatar_input.mjs';
import {AvatarMouseSphere,nearestEndpoint} from './avatar_mouse_sphere.mjs';
import {normalizeProfile} from './avatar_studio_settings.mjs';
import {normalizeGraphics,applyTextureFiltering} from './avatar_graphics.mjs';
test('click never begins dragging; crossing travel threshold latches exactly once',()=>{const input=new AvatarGesture();input.down({x:0,y:0},{bone:'head'});assert.equal(input.move({x:2,y:1},6),false);assert.equal(input.up().dragging,false);input.down({x:0,y:0},{bone:'head'});assert.equal(input.move({x:10,y:0},6),true);assert.equal(input.move({x:0,y:0},6),false);assert.equal(input.up().dragging,true);});
test('hover delay and off-hover fire once, including transitions between bones',()=>{const hover=new AvatarHover(),a={bone:'head'},b={bone:'leftHand'};assert.deepEqual(hover.update(a,0,500).map(e=>e.kind),['hover']);assert.deepEqual(hover.update(a,499,500),[]);assert.deepEqual(hover.update(a,500,500).map(e=>e.kind),['hoverDelayed']);assert.deepEqual(hover.update(a,600,500),[]);assert.deepEqual(hover.update(b,700,500).map(e=>e.kind),['leave','hover']);assert.deepEqual(hover.update(null,900,500).map(e=>e.kind),['leave']);});
function chain(){const scene=new Group(),root=new Bone(),middle=new Bone(),tail=new Bone();scene.add(root);root.add(middle);middle.add(tail);middle.position.y=1;tail.position.y=1;scene.updateMatrixWorld(true);const a={id:'root/0',node:root,joint:{child:middle}},b={id:'root/0/0',node:middle,joint:{child:tail}},catalog={entries:[a,b]},sphere=new AvatarMouseSphere(catalog,scene);return {scene,root,middle,tail,a,b,sphere};}
test('endpoint selection chooses only the nearest end and retains it through dragging',()=>{const {scene,root,middle,tail,b,sphere}=chain();assert.equal(nearestEndpoint(b,new Vector3(0,1,0)).node,middle);assert.equal(nearestEndpoint(b,new Vector3(0,2,0)).node,tail);sphere.position.set(.1,2,0);const endpoint=sphere.start(b);sphere.position.set(1,1,0);assert.equal(sphere.drag.endpoint,endpoint);assert.equal(endpoint.node,tail);const profile=normalizeProfile({mouseSphere:{radius:.01}});sphere.target.copy(sphere.position);sphere.active=true;sphere.initialized=true;for(let i=0;i<20;i++){sphere.restore();sphere.update(profile,1/60);scene.updateMatrixWorld(true);}assert.ok(root.position.length()===0);assert.ok(scene.position.length()===0);assert.ok(root.quaternion.angleTo(new Quaternion())>0);assert.equal(tail.position.y,1);sphere.restore();assert.ok(root.quaternion.angleTo(new Quaternion())<1e-7);});
test('head endpoint is pulled through upstream owner, not by translating both bones',()=>{const {a,b,middle,sphere}=chain();sphere.position.set(.1,1,0);assert.equal(sphere.start(b).node,middle);const torque=new Map();sphere.addTorque(torque,b,middle,new Vector3(1,0,0),[a,b],true);assert.ok(torque.has(a.id));assert.equal(torque.has(b.id),false);});
test('sphere spring and click bounce remain finite and return from Z bounce',()=>{const {sphere}=chain(),profile=normalizeProfile({});sphere.active=true;sphere.initialized=true;sphere.target.set(1,1,.1);sphere.position.copy(sphere.target);sphere.click();sphere.update(profile,.1);assert.ok(sphere.position.z<.1);for(let i=0;i<100;i++){sphere.restore();sphere.update(profile,1/60);}assert.ok(sphere.position.distanceTo(sphere.target)<.001);assert.ok(sphere.velocity.toArray().every(Number.isFinite));});
test('graphics settings are validated and anisotropy respects GPU limits',()=>{const g=normalizeGraphics({avatarGraphics:{antialias:false,samples:99,anisotropy:16,pixelRatio:99}}).avatarGraphics;assert.equal(g.antialias,false);assert.equal(g.samples,4);assert.equal(g.pixelRatio,2);const scene=new Group(),texture=new Texture();scene.add(new Mesh(new BoxGeometry(),new MeshBasicMaterial({map:texture})));assert.equal(applyTextureFiltering(scene,{capabilities:{getMaxAnisotropy:()=>4}},g),4);assert.equal(texture.anisotropy,4);});
