import React,{useEffect,useState} from 'react';
import {CATALOG_KEY,readCatalog,normalizeProfile,normalizeBone,importStudioPreset,importGLSL} from './avatar_studio_settings.mjs';

export default function AvatarStudio({preferences,update}){
 const [catalog,setCatalog]=useState(readCatalog),[bone,setBone]=useState(''),[query,setQuery]=useState(''),[error,setError]=useState('');
 useEffect(()=>{const refresh=()=>setCatalog(readCatalog());const storage=e=>{if(e.key===CATALOG_KEY)refresh();};window.addEventListener('storage',storage);window.addEventListener('avatar-catalog',refresh);return()=>{window.removeEventListener('storage',storage);window.removeEventListener('avatar-catalog',refresh);};},[]);
 useEffect(()=>{const select=e=>{if(typeof e.detail==='string')setBone(e.detail);};window.addEventListener('avatar-select-bone',select);return()=>window.removeEventListener('avatar-select-bone',select);},[]);
 const profile=normalizeProfile(preferences.avatarStudioProfiles?.[catalog?.key]);
 const entries=catalog?.bones||[],selected=entries.find(e=>e.id===bone)||entries[0],id=selected?.id;
 const rule=profile.bones[id]||normalizeBone(selected?.settings);
 const change=patch=>{if(catalog)update({avatarStudioProfiles:{...preferences.avatarStudioProfiles,[catalog.key]:{...profile,...patch}}});};
 const edit=patch=>change({bones:{...profile.bones,[id]:normalizeBone({...rule,...patch})}});
 const numeric=(label,value,change,min,max,step=.01)=><label className="setting-field"><span>{label}</span><input aria-label={label} type="number" min={min} max={max} step={step} value={value} onChange={e=>{if(e.target.value!==''&&Number.isFinite(e.target.valueAsNumber))change(e.target.valueAsNumber);}}/></label>;
 const toggle=(label,value,change)=><label className="setting-field toggle-field"><span>{label}</span><input type="checkbox" checked={value} onChange={e=>change(e.target.checked)}/></label>;
 const vector=(label,value,change,min,max)=><fieldset><legend>{label}</legend><div className="settings-grid">{['X','Y','Z'].map((axis,i)=><React.Fragment key={axis}>{numeric(label+' '+axis,value[i],n=>change(value.map((v,j)=>i===j?n:v)),min,max)}</React.Fragment>)}</div></fieldset>;
 const filtered=entries.filter(e=>(e.name+' '+e.human+' '+e.id).toLowerCase().includes(query.toLowerCase()));
 const pickupControls=<section><h3>Pickup, ragdoll & recovery</h3><p className="caption">Angular ragdoll: grabbed-bone anchoring, articulated gravity and pendulum motion. No ground or self-collision. Recovery begins on release.</p><div className="settings-grid">{toggle('Enable articulated pickup',profile.pickup.enabled,enabled=>change({pickup:{...profile.pickup,enabled}}))}{toggle('Enable threshold ragdoll',profile.pickup.ragdollEnabled,ragdollEnabled=>change({pickup:{...profile.pickup,ragdollEnabled}}))}{[['gravity','Gravity',0,30],['damping','Pickup damping',0,10],['bodySpring','Body follow spring',1,80],['inertia','Drag inertia',0,3],['maxSwing','Maximum body swing (degrees)',0,180],['jointLimit','Joint angular limit (degrees)',0,120],['distanceThreshold','Ragdoll distance threshold (px)',10,3000],['speedThreshold','Ragdoll speed threshold (px/s)',50,10000],['recoverySeconds','Recovery duration (seconds)',.2,10]].map(([key,label,min,max])=><React.Fragment key={key}>{numeric(label,profile.pickup[key],value=>change({pickup:{...profile.pickup,[key]:value}}),min,max,.1)}</React.Fragment>)}</div></section>;
 async function load(event){const file=event.target.files?.[0];event.target.value='';if(!file)return;
  try{if(file.size>262144)throw new Error('Import exceeds 256 KiB');const text=await file.text();
   if(/\.(glsl|frag)$/i.test(file.name))change({effect:{...profile.effect,glsl:importGLSL(text),glslEnabled:false}});
   else change(importStudioPreset(text));setError('');
  }catch(e){setError(e.message);}
 }
 function exportPreset(){const blob=new Blob([JSON.stringify({format:'riko-avatar-effects',version:1,lighting:profile.lighting,effect:{...profile.effect,glslEnabled:false}},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='avatar-effects.json';a.click();URL.revokeObjectURL(url);}
 return <section id="appearance-avatar-studio"><h2>Avatar physics, calibration & effects</h2><p className="caption">Runtime overrides only; imported skin weights, spring chains and original model files are preserved. Settings belong to the loaded model and skeleton. Load an avatar to discover all its bones.</p>
 {!catalog?<p role="status">No loaded avatar skeleton yet.</p>:<><p className="caption">Model: {catalog.source} · {entries.length} bones</p>
 <div className="settings-grid"><label className="setting-field">Search bones<input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="setting-field">Model bone<select value={id||''} onChange={e=>setBone(e.target.value)}>{(selected&&!filtered.includes(selected)?[selected,...filtered]:filtered).map(e=><option key={e.id} value={e.id}>{e.human||e.name}{e.spring?' · VRM spring':''} · {e.id}</option>)}</select></label>
 {toggle('Show skeleton debug view',profile.debug,debug=>change({debug}))}{toggle('Preview calibrated T-pose (pauses animation playback)',profile.tPose,tPose=>change({tPose}))}</div>
  <details><summary>Debug bone filters (none selected shows all)</summary><button onClick={()=>change({debugBones:[]})}>Show all bones</button>{filtered.map(e=><label key={e.id} className="avatar-bone-filter"><input type="checkbox" checked={profile.debugBones.includes(e.id)} onChange={event=>change({debugBones:event.target.checked?[...profile.debugBones,e.id]:profile.debugBones.filter(v=>v!==e.id)})}/>{e.human||e.name} · {e.id}</label>)}</details>
  <h3>Spring selection volumes</h3><p className="caption">Every imported spring joint has an animated capsule, including humanoid springs and terminal joints with virtual tails. Increase selection radius to make thin hair/accessory springs easier to grab. This only changes picking, not physics colliders. Enable hit-volume outlines under Interaction connections to see and filter the volumes.</p>{numeric('Spring selection radius (m)',profile.springPickRadius,springPickRadius=>change({springPickRadius}),.005,.2,.005)}
 {selected&&<><h3>Secondary motion · {selected.human||selected.name}</h3><p className="caption">Damped rotational follow-through layers onto animation. Enable only the bones you want; enabling it on an existing spring adds extra smoothing. This does not create new deforming bones or colliders.</p><div className="settings-grid">
 {toggle('Enable secondary motion',rule.enabled,enabled=>edit({enabled}))}{numeric('Motion blend',rule.amount,amount=>edit({amount}),0,1)}{numeric('Spring frequency (Hz)',rule.frequency,frequency=>edit({frequency}),.2,20,.1)}{numeric('Damping ratio',rule.damping,damping=>edit({damping}),0,2)}{numeric('Maximum angular lag (degrees)',rule.maxAngle,maxAngle=>edit({maxAngle}),0,90,1)}</div>
 <h3>T-pose calibration</h3><p className="caption">Local position offsets in metres are added on every animation frame. Large offsets can stretch the mesh; these are non-destructive adjustments, not changes to skin bind weights.</p>{vector('Bone position offset (m)',rule.offset,offset=>edit({offset}),-.5,.5)}
 {selected.spring&&<><h3>Imported VRM spring parameters</h3><div className="settings-grid">{toggle('Override imported spring parameters',rule.springOverride,springOverride=>edit({springOverride}))}{numeric('VRM stiffness',rule.stiffness,stiffness=>edit({stiffness}),0,10)}{numeric('VRM drag',rule.dragForce,dragForce=>edit({dragForce}),0,1)}{numeric('VRM gravity strength',rule.gravityPower,gravityPower=>edit({gravityPower}),0,5)}{numeric('VRM collision radius (m)',rule.hitRadius,hitRadius=>edit({hitRadius}),0,.5)}</div>{vector('VRM gravity direction',rule.gravityDir,gravityDir=>edit({gravityDir}),-1,1)}</>}
 <button onClick={()=>{const bones={...profile.bones};delete bones[id];change({bones});}}>Reset this bone</button></>}
 <h3>Model-space lighting</h3><div className="settings-grid">{numeric('Ambient intensity',profile.lighting.ambient,ambient=>change({lighting:{...profile.lighting,ambient}}),0,5)}{['sky','ground'].map(key=><label className="setting-field" key={key}>Ambient {key} color<input type="color" value={profile.lighting[key]} onChange={e=>change({lighting:{...profile.lighting,[key]:e.target.value}})}/></label>)}</div>
 {profile.lighting.lights.map((light,i)=>{const editLight=patch=>change({lighting:{...profile.lighting,lights:profile.lighting.lights.map((value,j)=>i===j?{...value,...patch}:value)}});return <fieldset key={i}><legend>Light {i+1}</legend><div className="settings-grid"><label className="setting-field">Light type<select value={light.type} onChange={e=>editLight({type:e.target.value})}><option value="point">Point</option><option value="directional">Directional</option></select></label><label className="setting-field">Light color<input type="color" value={light.color} onChange={e=>editLight({color:e.target.value})}/></label>{numeric('Light '+(i+1)+' intensity',light.intensity,intensity=>editLight({intensity}),0,20)}</div>{vector('Light '+(i+1)+' position (m)',light.position,position=>editLight({position}),-10,10)}<button onClick={()=>change({lighting:{...profile.lighting,lights:profile.lighting.lights.filter((_,j)=>j!==i)}})}>Remove light {i+1}</button></fieldset>;})}
 <button disabled={profile.lighting.lights.length>=8} onClick={()=>change({lighting:{...profile.lighting,lights:[...profile.lighting.lights,{type:'point',color:'#ffffff',intensity:1,position:[1,2,2]}]}})}>Add light</button>
 <h3>Shader effects</h3><p className="caption">Effects preserve VRM materials and canvas transparency. Import a JSON effect preset or a .glsl/.frag file defining vec4 avatarEffect(vec4 color, vec2 uv, float time). GLSL is a screen-space color effect, not a replacement skinning shader. Loops/includes are unsupported. Custom GPU code can still stall rendering; use only trusted files.</p><div className="settings-grid"><label className="setting-field">Color effect<select value={profile.effect.preset} onChange={e=>change({effect:{...profile.effect,preset:e.target.value}})}>{['none','warm','cool','monochrome'].map(v=><option key={v}>{v}</option>)}</select></label>{numeric('Exposure multiplier',profile.effect.exposure,exposure=>change({effect:{...profile.effect,exposure}}),0,3)}{numeric('Color saturation',profile.effect.saturation,saturation=>change({effect:{...profile.effect,saturation}}),0,2)}
 {toggle('Enable imported GLSL (trusted GPU code only)',profile.effect.glslEnabled,glslEnabled=>change({effect:{...profile.effect,glslEnabled}}))}<label className="setting-field">Import effect preset or GLSL<input type="file" accept=".json,.glsl,.frag" onChange={load}/></label></div><p className="caption">{profile.effect.glsl?'Custom GLSL loaded ('+profile.effect.glsl.length+' characters). Importing never enables it automatically.':'No custom GLSL loaded.'}</p><button onClick={exportPreset}>Export effect preset</button><button onClick={()=>change({effect:{...profile.effect,glsl:'',glslEnabled:false}})}>Remove custom GLSL</button>
  <h3>Spring bone dragging</h3><p className="caption">The endpoint nearest the initial click is retained throughout the drag, including virtual spring tails. The cursor pulls at that endpoint’s depth, without an initial jump. Strength controls how firmly eligible joints follow the cursor; 0 disables the pull. Fixed rig attachments stay fixed. Dragging works even when mouse sphere pushing is disabled.</p><div className="settings-grid">{numeric('Spring drag strength',profile.mouseSphere.dragSpring,dragSpring=>change({mouseSphere:{...profile.mouseSphere,dragSpring}}),0,100,1)}<label className="setting-field">Spring drag strength slider<input aria-label="Spring drag strength slider" type="range" min="0" max="100" step="1" value={profile.mouseSphere.dragSpring} onChange={e=>change({mouseSphere:{...profile.mouseSphere,dragSpring:e.target.valueAsNumber}})}/></label></div>
  <h3>Mouse force sphere & gestures</h3><p className="caption">The sphere follows the mouse with spring smoothing, slightly in front of the model. A click bounces it in Z. Sphere push strength is separate from spring dragging strength.</p><div className="settings-grid">{toggle('Enable mouse force sphere',profile.mouseSphere.enabled,enabled=>change({mouseSphere:{...profile.mouseSphere,enabled}}))}{toggle('Show mouse sphere',profile.mouseSphere.debug,debug=>change({mouseSphere:{...profile.mouseSphere,debug}}))}{[['radius','Sphere radius (m)',.01,1],['depth','Sphere front depth (m)',-.5,.5],['strength','Sphere push strength',0,50],['frequency','Mouse follow frequency (Hz)',.5,20],['damping','Mouse follow damping',.1,2],['bounce','Click Z bounce (m)',0,.5],['bounceSeconds','Click bounce duration (s)',.1,2],['maxAngle','Sphere joint angular limit (degrees)',0,90]].map(([key,label,min,max])=><React.Fragment key={key}>{numeric(label,profile.mouseSphere[key],value=>change({mouseSphere:{...profile.mouseSphere,[key]:value}}),min,max)}</React.Fragment>)}{numeric('Drag activation distance (px)',profile.input.dragThreshold,dragThreshold=>change({input:{...profile.input,dragThreshold}}),2,50,1)}{numeric('Delayed hover (ms)',profile.input.hoverDelay,hoverDelay=>change({input:{...profile.input,hoverDelay}}),0,5000,50)}</div>
  <h3>Eye tracking & pupil convergence</h3><p className="caption">Eyes follow the mouse sphere. Nearby targets increase convergence (apparent pupil spacing); eye positions and anatomical IPD stay unchanged. A mouse has no physical depth, so target distance comes from the sphere/depth settings. Expression-only VRMs support shared gaze but cannot converge each eye independently.</p><div className="settings-grid">{toggle('Enable mouse eye tracking',profile.gaze.enabled,enabled=>change({gaze:{...profile.gaze,enabled}}))}{toggle('Enable distance-based pupil convergence',profile.gaze.convergence,convergence=>change({gaze:{...profile.gaze,convergence}}))}{[['strength','Convergence strength',0,3],['smoothing','Gaze smoothing response',1,30],['minDistance','Minimum eye target distance (m)',.05,1],['maxYaw','Maximum gaze yaw (degrees)',0,90],['maxPitch','Maximum gaze pitch (degrees)',0,60],['maxConvergence','Maximum convergence per eye (degrees)',0,30]].map(([key,label,min,max])=><React.Fragment key={key}>{numeric(label,profile.gaze[key],value=>change({gaze:{...profile.gaze,[key]:value}}),min,max)}</React.Fragment>)}</div>
  {pickupControls}<button onClick={()=>change(normalizeProfile({}))}>Reset this model’s runtime overrides</button></>}
 {error&&<p role="alert">{error}</p>}
 </section>;
}
