import React,{useEffect,useState} from 'react';
import {request} from './api.mjs';
import {connectEvents} from './event_connection.mjs';
import DiscordLaunch from './discord_launch.jsx';
export default function DiscordSettings(){
 const [snapshot,setSnapshot]=useState(null),[draft,setDraft]=useState({}),[messages,setMessages]=useState([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const [settings,inbox]=await Promise.all([request('/api/discord/settings'),request('/api/discord/inbox')]);setSnapshot(settings);setDraft({...settings.values,...Object.fromEntries(['admins','users','channels'].map(key=>[key,settings.values[key].join('\n')]))});setMessages(inbox.messages);}catch(e){setError(e.message);}}
 useEffect(()=>{load();return connectEvents(e=>{if(e.type==='discord.message_seen')setMessages(old=>[e.payload,...old.filter(m=>m.id!==e.payload.id)].slice(0,256));});},[]);
 function add(key,id){setDraft(old=>({...old,[key]:[...new Set([...old[key].split(/[\s,]+/).filter(Boolean),id])].join('\n')}));setNotice('Added to draft. Save to apply.');}
 async function save(){setBusy(true);setError('');try{const values={...draft,...Object.fromEntries(['admins','users','channels'].map(key=>[key,draft[key].split(/[\s,]+/).filter(Boolean)]))};const result=await request('/api/discord/settings',{method:'PUT',body:{values,revision:snapshot.revision}});setSnapshot(result);setNotice('Saved. New requests use this policy immediately.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section id="settings-discord" tabIndex={-1}><DiscordLaunch onError={setError}/><button onClick={()=>request('/api/discord/stop-client',{method:'POST'}).catch(e=>setError(e.message))}>Stop managed client</button><p>Credentials stay in the local .env (Discord_bot_token). Enable Message Content Intent in the Discord developer portal. User/admin access and channel access are both required in servers.</p>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{snapshot&&<><div className="settings-grid">{[['users','Whitelisted users'],['admins','Administrators'],['channels','Whitelisted channels']].map(([key,label])=><label className="setting-field" key={key}>{label}<textarea value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/><small>Discord IDs, separated by lines or commas. Developer Mode → Copy ID.</small></label>)}{[['allow_dms','Allow trusted users in direct messages'],['admin_actions','Allow administrators to use administrative commands']].map(([key,label])=><label key={key}>{label}<input type="checkbox" checked={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.checked})}/></label>)}</div><button disabled={busy} onClick={save}>Save Discord settings</button></>}<button onClick={load}>Reload Discord settings and inbox</button><h3>Messages seen by Discord</h3><p>Latest 256 received messages, including blocked users and ignored bots. Only permitted messages reach the model. This inbox is temporary; Discord cannot expose channels it cannot read.</p>{messages.map(m=><article key={m.id}><strong>{m.user_name} · {m.channel_name} · {m.status}</strong><p style={{whiteSpace:'pre-wrap'}}>{m.text}</p>{m.attachments?.join(', ')}<div><button disabled={!snapshot} onClick={()=>add('users',m.user_id)}>Whitelist user</button><button disabled={!snapshot} onClick={()=>add('admins',m.user_id)}>Make admin</button><button disabled={!snapshot} onClick={()=>add('channels',m.channel_id)}>Whitelist channel</button></div></article>)}</section>;
}
