from __future__ import annotations

from typing import Iterable, Protocol, Sequence

from ..conversation.messages import ChatMessage, ModelResponse


class ModelProvider(Protocol):
    def generate(self, messages: Sequence[ChatMessage], *, tools: list[dict] | None = None, **options) -> ModelResponse: ...
    def stream(self, messages: Sequence[ChatMessage], *, tools: list[dict] | None = None, **options) -> Iterable[str]: ...
    def count_tokens(self, messages: Sequence[ChatMessage]) -> int: ...
    def close(self) -> None: ...
